lsi: false
safe: true
incremental: false
markdown: kramdown
highlighter: rouge
gist:
  noscript: false

# Permalinks
permalink:	/blog/:title

# Setup
title:            Curveball
tagline:          'A framework that rips'
description:      'A javascript framework for building webservices in Node.js'
url:              https://curveballjs.org
baseurl:

author:
  name:           Evert Pot
  url:            https://evertpot.com

include: ['_sass', '*.scss']

copyright:
  author:         Curveball
  url:            https://github.com/curveball

# Custom vars
icon:             /assets/images/logo.svg
cover:            /assets/images/cover-3.jpg

social:
  # - icon:         twitter
  #   url:          https://twitter.com/curveballjs
  #   desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/curveball/core
    desc:         Fork me on github

  - icon:         feed
    url:          https://curveballjs.org/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /
  - title:        Docs
    url:          /docs

collections_dir: collections
collections:
  getting-started:
    output: true
    order: 
    - basics.md
    - aws-lamdba.md
    - azure.md
    - bun.md
    - node.md
  middleware:
    output: true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
