lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink:	/blog/:title

# Setup
title:            Curveball
tagline:          'A framework that rips'
description:      'A javascript framework for building webservices in Node.js'
url:              http://curveballjs.org
baseurl:          

author:
  name:           Evert Pot
  url:            https://evertpot.com

include: ['_sass', '*.scss']

# Custom vars
icon:             /assets/images/logo.svg
cover:            /assets/images/cover-3.jpg

social:
  # - icon:         twitter
  #   url:          https://twitter.com/curveballjs
  #   desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/curveballjs
    desc:         Fork me on github

  - icon:         feed
    url:          https://curveballjs.org/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
